--
-- Target: Microsoft SQL Server 
-- Syntax: isql /Uuser /Ppassword /Sserver -i\path\filename.sql
-- Date  : Feb 20 2017 13:05
-- Script Generated by Database Design Studio 2.21.3 
--


--
-- Select Database: 'HandIn2DAB'
--
USE HandIn2DAB
GO
 
IF DB_NAME() = 'HandIn2DAB'
    RAISERROR('''HandIn2DAB'' DATABASE CONTEXT NOW IN USE.',1,1)
ELSE
    RAISERROR('ERROR IN BATCH FILE, ''USE db_name'' FAILED!  KILLING THE SPID NOW.',22,127) WITH LOG
 
GO
EXECUTE SP_DBOPTION 'db_name' ,'TRUNC. LOG ON CHKPT.' ,'TRUE'
GO

--
-- Create Table    : 'Adresse'   
-- AdresseId       :  
-- Vejnavn         :  
-- HusNr           :  
-- PostNr          :  
-- Bynavn          :  
-- Type            :  
--
CREATE TABLE Adresse (
    AdresseId      BIGINT NOT NULL UNIQUE,
    Vejnavn        VARCHAR NOT NULL,
    HusNr          BIGINT NOT NULL,
    PostNr         BIGINT NOT NULL,
    Bynavn         VARCHAR NOT NULL,
    Type           VARCHAR NOT NULL,
CONSTRAINT pk_Adresse PRIMARY KEY CLUSTERED (AdresseId))
GO

--
-- Create Table    : 'Person'   
-- PersonId        :  
-- Fornavn         :  
-- Mellemnavn      :  
-- Efternavn       :  
-- Type            :  
-- AdresseId       :  (references Adresse.AdresseId)
--
CREATE TABLE Person (
    PersonId       BIGINT NOT NULL UNIQUE,
    Fornavn        NVARCHAR(255) NOT NULL,
    Mellemnavn     NVARCHAR(255) NULL,
    Efternavn      NVARCHAR(255) NOT NULL,
    Type           NVARCHAR(255) NOT NULL,
    AdresseId      BIGINT NOT NULL,
CONSTRAINT pk_Person PRIMARY KEY CLUSTERED (PersonId),
CONSTRAINT fk_Person FOREIGN KEY (AdresseId)
    REFERENCES Adresse (AdresseId)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
GO

--
-- Create Table    : 'TelefonNr'   
-- TelefonId       :  
-- Type            :  
-- Nummer          :  
-- PersonId        :  (references Person.PersonId)
--
CREATE TABLE TelefonNr (
    TelefonId      BIGINT NOT NULL,
    Type           VARCHAR NOT NULL,
    Nummer         BIGINT NOT NULL,
    PersonId       BIGINT NOT NULL,
CONSTRAINT pk_TelefonNr PRIMARY KEY CLUSTERED (TelefonId),
CONSTRAINT fk_TelefonNr FOREIGN KEY (PersonId)
    REFERENCES Person (PersonId)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
GO

--
-- Create Table    : 'HarAdresse'   
-- AdresseId       :  (references Adresse.AdresseId)
-- PersonId        :  (references Person.PersonId)
-- Type            :  
--
CREATE TABLE HarAdresse (
    AdresseId      BIGINT NOT NULL,
    PersonId       BIGINT NOT NULL,
    Type           NVARCHAR(255) NOT NULL,
CONSTRAINT pk_HarAdresse PRIMARY KEY CLUSTERED (AdresseId,PersonId),
CONSTRAINT fk_HarAdresse FOREIGN KEY (AdresseId)
    REFERENCES Adresse (AdresseId)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
CONSTRAINT fk_HarAdresse2 FOREIGN KEY (PersonId)
    REFERENCES Person (PersonId)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
GO

--
-- Permissions for: 'public'
--
GRANT ALL ON Adresse TO public
GO
GRANT ALL ON Person TO public
GO
GRANT ALL ON TelefonNr TO public
GO
GRANT ALL ON HarAdresse TO public
GO

